*------------------------------------------------------------------------------------------------------------------------*
*--@title:			KeyBoard Class
*--@description:	Sustituye los valores correspondientes a las pulsaciones de teclas por constantes
*--@autor:			Irwin R. <irwinrodriguez@adsecuador.com>
*--@version:		SNV: 1.2.0
*--@date:			2019-01-11
*------------------------------------------------------------------------------------------------------------------------*
DEFINE CLASS KEYBOARD AS CUSTOM
*-- Properties Lists
	VK_F1_ALONE							=	28
	VK_F1_SHIFT							=	84
	VK_F1_CTRL							=	94
	VK_F1_ALT							=	104

	VK_F2_ALONE							=	-1
	VK_F2_SHIFT							=	85
	VK_F2_CTRL							=	95
	VK_F2_ALT							=	105

	VK_F3_ALONE							=	-2
	VK_F3_SHIFT							=	86
	VK_F3_CTRL							=	96
	VK_F3_ALT							=	106

	VK_F4_ALONE							=	-3
	VK_F4_SHIFT							=	87
	VK_F4_CTRL							=	97
	VK_F4_ALT							=	107

	VK_F5_ALONE							=	-4
	VK_F5_SHIFT							=	88
	VK_F5_CTRL							=	98
	VK_F5_ALT							=	108

	VK_F6_ALONE							=	-5
	VK_F6_SHIFT							=	89
	VK_F6_CTRL							=	99
	VK_F6_ALT							=	109

	VK_F7_ALONE							=	-6
	VK_F7_SHIFT							=	90
	VK_F7_CTRL							=	100
	VK_F7_ALT							=	110

	VK_F8_ALONE							=	-7
	VK_F8_SHIFT							=	91
	VK_F8_CTRL							=	101
	VK_F8_ALT							=	111

	VK_F9_ALONE							=	-8
	VK_F9_SHIFT							=	92
	VK_F9_CTRL							=	102
	VK_F9_ALT							=	112

	VK_F10_ALONE						=	-9
	VK_F10_SHIFT						=	93
	VK_F10_CTRL							=	103
	VK_F10_ALT							=	113

	VK_F11_ALONE						=	133
	VK_F11_SHIFT						=	135
	VK_F11_CTRL							=	137
	VK_F11_ALT							=	139

	VK_F12_ALONE						=	134
	VK_F12_SHIFT						=	136
	VK_F12_CTRL							=	138
	VK_F12_ALT							=	140

	VK_1_ALONE							=	49
	VK_1_SHIFT							=	33
	VK_1_CTRL							=	0
	VK_1_ALT							=	120

	VK_2_ALONE							=	50
	VK_2_SHIFT							=	64
	VK_2_CTRL							=	0
	VK_2_ALT							=	121

	VK_3_ALONE							=	51
	VK_3_SHIFT							=	35
	VK_3_CTRL							=	0
	VK_3_ALT							=	122

	VK_4_ALONE							=	52
	VK_4_SHIFT							=	36
	VK_4_CTRL							=	0
	VK_4_ALT							=	123

	VK_5_ALONE							=	53
	VK_5_SHIFT							=	37
	VK_5_CTRL							=	0
	VK_5_ALT							=	124

	VK_6_ALONE							=	54
	VK_6_SHIFT							=	94
	VK_6_CTRL							=	0
	VK_6_ALT							=	125

	VK_7_ALONE							=	55
	VK_7_SHIFT							=	38
	VK_7_CTRL							=	0
	VK_7_ALT							=	126

	VK_8_ALONE							=	56
	VK_8_SHIFT							=	42
	VK_8_CTRL							=	0
	VK_8_ALT							=	127

	VK_9_ALONE							=	57
	VK_9_SHIFT							=	40
	VK_9_CTRL							=	0
	VK_9_ALT							=	128

	VK_0_ALONE							=	48
	VK_0_SHIFT							=	41
	VK_0_CTRL							=	0
	VK_0_ALT							=	19

	VK_A_ALONE							=	97
	VK_A_SHIFT							=	65
	VK_A_CTRL							=	1
	VK_A_ALT							=	30

	VK_B_ALONE							=	98
	VK_B_SHIFT							=	66
	VK_B_CTRL							=	2
	VK_B_ALT							=	48

	VK_C_ALONE							=	99
	VK_C_SHIFT							=	67
	VK_C_CTRL							=	3
	VK_C_ALT							=	46

	VK_D_ALONE							=	100
	VK_D_SHIFT							=	68
	VK_D_CTRL							=	4
	VK_D_ALT							=	32

	VK_E_ALONE							=	101
	VK_E_SHIFT							=	69
	VK_E_CTRL							=	5
	VK_E_ALT							=	18

	VK_F_ALONE							=	102
	VK_F_SHIFT							=	70
	VK_F_CTRL							=	6
	VK_F_ALT							=	33

	VK_G_ALONE							=	103
	VK_G_SHIFT							=	71
	VK_G_CTRL							=	7
	VK_G_ALT							=	34

	VK_H_ALONE							=	104
	VK_H_SHIFT							=	72
	VK_H_CTRL							=	127
	VK_H_ALT							=	35

	VK_I_ALONE							=	105
	VK_I_SHIFT							=	73
	VK_I_CTRL							=	9
	VK_I_ALT							=	23

	VK_J_ALONE							=	106
	VK_J_SHIFT							=	74
	VK_J_CTRL							=	10
	VK_J_ALT							=	36

	VK_K_ALONE							=	107
	VK_K_SHIFT							=	75
	VK_K_CTRL							=	11
	VK_K_ALT							=	37

	VK_L_ALONE							=	108
	VK_L_SHIFT							=	76
	VK_L_CTRL							=	12
	VK_L_ALT							=	38

	VK_M_ALONE							=	109
	VK_M_SHIFT							=	77
	VK_M_CTRL							=	13
	VK_M_ALT							=	50

	VK_N_ALONE							=	110
	VK_N_SHIFT							=	78
	VK_N_CTRL							=	14
	VK_N_ALT							=	49

	VK_O_ALONE							=	111
	VK_O_SHIFT							=	79
	VK_O_CTRL							=	15
	VK_O_ALT							=	24

	VK_P_ALONE							=	112
	VK_P_SHIFT							=	80
	VK_P_CTRL							=	16
	VK_P_ALT							=	25

	VK_Q_ALONE							=	113
	VK_Q_SHIFT							=	81
	VK_Q_CTRL							=	17
	VK_Q_ALT							=	16

	VK_R_ALONE							=	114
	VK_R_SHIFT							=	82
	VK_R_CTRL							=	18
	VK_R_ALT							=	19

	VK_S_ALONE							=	115
	VK_S_SHIFT							=	83
	VK_S_CTRL							=	19
	VK_S_ALT							=	31

	VK_T_ALONE							=	116
	VK_T_SHIFT							=	84
	VK_T_CTRL							=	20
	VK_T_ALT							=	20

	VK_U_ALONE							=	117
	VK_U_SHIFT							=	85
	VK_U_CTRL							=	21
	VK_U_ALT							=	22

	VK_V_ALONE							=	118
	VK_V_SHIFT							=	86
	VK_V_CTRL							=	22
	VK_V_ALT							=	47

	VK_W_ALONE							=	119
	VK_W_SHIFT							=	87
	VK_W_CTRL							=	23
	VK_W_ALT							=	17

	VK_X_ALONE							=	120
	VK_X_SHIFT							=	88
	VK_X_CTRL							=	24
	VK_X_ALT							=	45

	VK_Y_ALONE							=	121
	VK_Y_SHIFT							=	89
	VK_Y_CTRL							=	25
	VK_Y_ALT							=	21

	VK_Z_ALONE							=	122
	VK_Z_SHIFT							=	90
	VK_Z_CTRL							=	26
	VK_Z_ALT							=	44

	VK_INS_ALONE						=	22
	VK_INS_SHIFT						=	22
	VK_INS_CTRL							=	146
	VK_INS_ALT							=	162

	VK_HOME_ALONE						=	1
	VK_HOME_SHIFT						=	55
	VK_HOME_CTRL						=	29
	VK_HOME_ALT							=	151

	VK_DEL_ALONE						=	7
	VK_DEL_SHIFT						=	7
	VK_DEL_CTRL							=	147
	VK_DEL_ALT							=	163

	VK_END_ALONE						=	6
	VK_END_SHIFT						=	49
	VK_END_CTRL							=	23
	VK_END_ALT							=	159

	VK_PAGE_UP_ALONE					=	18
	VK_PAGE_UP_SHIFT					=	57
	VK_PAGE_UP_CTRL						=	31
	VK_PAGE_UP_ALT						=	153

	VK_PAGE_DOWN_ALONE					=	3
	VK_PAGE_DOWN_SHIFT					=	51
	VK_PAGE_DOWN_CTRL					= 	30
	VK_PAGE_DOWN_ALT					= 	161

	VK_UP_ARROW_ALONE					=	5
	VK_UP_ARROW_SHIFT					=	56
	VK_UP_ARROW_CTRL					=	141
	VK_UP_ARROW_ALT						=	152

	VK_DOWN_ARROW_ALONE					=	24
	VK_DOWN_ARROW_SHIFT					=	50
	VK_DOWN_ARROW_CTRL					=	145
	VK_DOWN_ARROW_ALT					=	160

	VK_RIGHT_ARROW_ALONE				=	4
	VK_RIGHT_ARROW_SHIFT				=	54
	VK_RIGHT_ARROW_CTRL					=	2
	VK_RIGHT_ARROW_ALT					=	157

	VK_LEFT_ARROW_ALONE					=	19
	VK_LEFT_ARROW_SHIFT					=	52
	VK_LEFT_ARROW_CTRL					=	26
	VK_LEFT_ARROW_ALT					=	155

	VK_ESC_ALONE						=	27
	VK_ESC_SHIFT						=	0
	VK_ESC_CTRL							=	0
	VK_ESC_ALT							=	0

	VK_ENTER_ALONE						=	13
	VK_ENTER_SHIFT						=	13
	VK_ENTER_CTRL						=	10
	VK_ENTER_ALT						=	0

	VK_BACKSPACE_ALONE					=	127
	VK_BACKSPACE_SHIFT					=	127
	VK_BACKSPACE_CTRL					=	127
	VK_BACKSPACE_ALT					=	14

	VK_TAB_ALONE						=	9
	VK_TAB_SHIFT						=	15
	VK_TAB_CTRL							=	0
	VK_TAB_ALT							=	0

	VK_SPACEBAR_ALONE					=	32
	VK_SPACEBAR_SHIFT					=	32
	VK_SPACEBAR_CTRL					=	0
	VK_SPACEBAR_ALT						=	57

	VK_ACCENT_OR_NMARK_ALONE			=	96
	VK_ACCENT_OR_NMARK_SHIFT			=	126
	VK_ACCENT_OR_NMARK_CTRL				=	0
	VK_ACCENT_OR_NMARK_ALT				=	41

	VK_MIDDLE_LINE_OR_DOWN_LINE_ALONE	=	45
	VK_MIDDLE_LINE_OR_DOWN_LINE_SHIFT	=	95
	VK_MIDDLE_LINE_OR_DOWN_LINE_CTRL	=	0
	VK_MIDDLE_LINE_OR_DOWN_LINE_ALT		=	0

	VK_EQUAL_OR_PLUS_ALONE				=	61
	VK_EQUAL_OR_PLUS_SHIFT				=	43
	VK_EQUAL_OR_PLUS_CTRL				=	0
	VK_EQUAL_OR_PLUS_ALT				=	13

	VK_OPEN_BRACE_ALONE					=	91
	VK_OPEN_BRACE_SHIFT					=	123
	VK_OPEN_BRACE_CTRL					=	27
	VK_OPEN_BRACE_ALT					=	26

	VK_CLOSE_BRACE_ALONE				=	93
	VK_CLOSE_BRACE_SHIFT				=	125
	VK_CLOSE_BRACE_CTRL					=	29
	VK_CLOSE_BRACE_ALT					=	27

	VK_CLOSE_BRACE_ALONE				=	93
	VK_CLOSE_BRACE_SHIFT				=	125
	VK_CLOSE_BRACE_CTRL					=	29
	VK_CLOSE_BRACE_ALT					=	27

	VK_BACK_SLASH_OR_PIPELINE_ALONE		=	92
	VK_BACK_SLASH_OR_PIPELINE_SHIFT		=	124
	VK_BACK_SLASH_OR_PIPELINE_CTRL		=	28
	VK_BACK_SLASH_OR_PIPELINE_ALT		=	43

	VK_SEMICOLON_OR_DOUBLE_POINT_ALONE	=	59
	VK_SEMICOLON_OR_DOUBLE_POINT_SHIFT	=	58
	VK_SEMICOLON_OR_DOUBLE_POINT_CTRL	=	0
	VK_SEMICOLON_OR_DOUBLE_POINT_ALT	=	39

	VK_COMMA_OR_SMALLER_THAN_ALONE		=	44
	VK_COMMA_OR_SMALLER_THAN_SHIFT		=	60
	VK_COMMA_OR_SMALLER_THAN_CTRL		=	0
	VK_COMMA_OR_SMALLER_THAN_ALT		=	51

	VK_SLASH_OR_QUESTION_MARK_ALONE		=	47
	VK_SLASH_OR_QUESTION_MARK_SHIFT		=	63
	VK_SLASH_OR_QUESTION_MARK_CTRL		=	0
	VK_SLASH_OR_QUESTION_MARK_ALT		=	53

	FUNCTION VK_F1_ALONE_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_F1_SHIFT_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_F1_CTRL_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_F1_ALT_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_F2_ALONE_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_F2_SHIFT_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_F2_CTRL_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_F2_ALT_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_F3_ALONE_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_F3_SHIFT_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_F3_CTRL_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_F3_ALT_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_F4_ALONE_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_F4_SHIFT_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_F4_CTRL_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_F4_ALT_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_F5_ALONE_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_F5_SHIFT_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_F5_CTRL_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_F5_ALT_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_F6_ALONE_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_F6_SHIFT_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_F6_CTRL_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_F6_ALT_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_F7_ALONE_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_F7_SHIFT_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_F7_CTRL_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_F7_ALT_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_F8_ALONE_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_F8_SHIFT_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_F8_CTRL_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_F8_ALT_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_F9_ALONE_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_F9_SHIFT_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_F9_CTRL_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_F9_ALT_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_F10_ALONE_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_F10_SHIFT_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_F10_CTRL_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_F10_ALT_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_F11_ALONE_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_F11_SHIFT_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_F11_CTRL_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_F11_ALT_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_F12_ALONE_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_F12_SHIFT_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_F12_CTRL_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_F12_ALT_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_1_ALONE_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_1_SHIFT_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_1_CTRL_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_1_ALT_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_2_ALONE_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_2_SHIFT_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_2_CTRL_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_2_ALT_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_3_ALONE_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_3_SHIFT_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_3_CTRL_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_3_ALT_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_4_ALONE_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_4_SHIFT_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_4_CTRL_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_4_ALT_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_5_ALONE_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_5_SHIFT_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_5_CTRL_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_5_ALT_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_6_ALONE_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_6_SHIFT_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_6_CTRL_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_6_ALT_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_7_ALONE_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_7_SHIFT_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_7_CTRL_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_7_ALT_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_8_ALONE_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_8_SHIFT_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_8_CTRL_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_8_ALT_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_9_ALONE_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_9_SHIFT_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_9_CTRL_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_9_ALT_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_0_ALONE_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_0_SHIFT_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_0_CTRL_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_0_ALT_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_A_ALONE_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_A_SHIFT_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_A_CTRL_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_A_ALT_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_B_ALONE_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_B_SHIFT_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_B_CTRL_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_B_ALT_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_C_ALONE_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_C_SHIFT_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_C_CTRL_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_C_ALT_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_D_ALONE_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_D_SHIFT_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_D_CTRL_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_D_ALT_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_E_ALONE_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_E_SHIFT_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_E_CTRL_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_E_ALT_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_F_ALONE_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_F_SHIFT_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_F_CTRL_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_F_ALT_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_G_ALONE_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_G_SHIFT_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_G_CTRL_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_G_ALT_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_H_ALONE_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_H_SHIFT_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_H_CTRL_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_H_ALT_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_I_ALONE_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_I_SHIFT_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_I_CTRL_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_I_ALT_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_J_ALONE_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_J_SHIFT_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_J_CTRL_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_J_ALT_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_K_ALONE_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_K_SHIFT_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_K_CTRL_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_K_ALT_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_L_ALONE_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_L_SHIFT_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_L_CTRL_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_L_ALT_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_M_ALONE_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_M_SHIFT_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_M_CTRL_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_M_ALT_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_N_ALONE_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_N_SHIFT_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_N_CTRL_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_N_ALT_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_O_ALONE_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_O_SHIFT_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_O_CTRL_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_O_ALT_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_P_ALONE_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_P_SHIFT_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_P_CTRL_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_P_ALT_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_Q_ALONE_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_Q_SHIFT_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_Q_CTRL_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_Q_ALT_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_R_ALONE_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_R_SHIFT_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_R_CTRL_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_R_ALT_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_S_ALONE_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_S_SHIFT_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_S_CTRL_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_S_ALT_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_T_ALONE_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_T_SHIFT_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_T_CTRL_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_T_ALT_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_U_ALONE_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_U_SHIFT_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_U_CTRL_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_U_ALT_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_V_ALONE_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_V_SHIFT_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_V_CTRL_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_V_ALT_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_W_ALONE_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_W_SHIFT_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_W_CTRL_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_W_ALT_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_X_ALONE_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_X_SHIFT_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_X_CTRL_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_X_ALT_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_Y_ALONE_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_Y_SHIFT_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_Y_CTRL_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_Y_ALT_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_Z_ALONE_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_Z_SHIFT_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_Z_CTRL_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_Z_ALT_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_INS_ALONE_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_INS_SHIFT_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_INS_CTRL_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_INS_ALT_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_HOME_ALONE_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_HOME_SHIFT_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_HOME_CTRL_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_HOME_ALT_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_DEL_ALONE_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_DEL_SHIFT_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_DEL_CTRL_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_DEL_ALT_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_END_ALONE_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_END_SHIFT_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_END_CTRL_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_END_ALT_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_PAGE_UP_ALONE_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_PAGE_UP_SHIFT_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_PAGE_UP_CTRL_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_PAGE_UP_ALT_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_PAGE_DOWN_ALONE_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_PAGE_DOWN_SHIFT_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_PAGE_DOWN_CTRL_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_PAGE_DOWN_ALT_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_UP_ARROW_ALONE_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_UP_ARROW_SHIFT_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_UP_ARROW_CTRL_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_UP_ARROW_ALT_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_DOWN_ARROW_ALONE_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_DOWN_ARROW_SHIFT_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_DOWN_ARROW_CTRL_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_DOWN_ARROW_ALT_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_RIGHT_ARROW_ALONE_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_RIGHT_ARROW_SHIFT_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_RIGHT_ARROW_CTRL_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_RIGHT_ARROW_ALT_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_LEFT_ARROW_ALONE_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_LEFT_ARROW_SHIFT_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_LEFT_ARROW_CTRL_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_LEFT_ARROW_ALT_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_ESC_ALONE_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_ESC_SHIFT_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_ESC_CTRL_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_ESC_ALT_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_ENTER_ALONE_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_ENTER_SHIFT_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_ENTER_CTRL_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_ENTER_ALT_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_BACKSPACE_ALONE_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_BACKSPACE_SHIFT_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_BACKSPACE_CTRL_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_BACKSPACE_ALT_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_TAB_ALONE_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_TAB_SHIFT_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_TAB_CTRL_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_TAB_ALT_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_SPACEBAR_ALONE_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_SPACEBAR_SHIFT_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_SPACEBAR_CTRL_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_SPACEBAR_ALT_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_ACCENT_OR_NMARK_ALONE_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_ACCENT_OR_NMARK_SHIFT_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_ACCENT_OR_NMARK_CTRL_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_ACCENT_OR_NMARK_ALT_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_MIDDLE_LINE_OR_DOWN_LINE_ALONE_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_MIDDLE_LINE_OR_DOWN_LINE_SHIFT_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_MIDDLE_LINE_OR_DOWN_LINE_CTRL_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_MIDDLE_LINE_OR_DOWN_LINE_ALT_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_EQUAL_OR_PLUS_ALONE_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_EQUAL_OR_PLUS_SHIFT_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_EQUAL_OR_PLUS_CTRL_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_EQUAL_OR_PLUS_ALT_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_OPEN_BRACE_ALONE_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_OPEN_BRACE_SHIFT_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_OPEN_BRACE_CTRL_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_OPEN_BRACE_ALT_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_CLOSE_BRACE_ALONE_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_CLOSE_BRACE_SHIFT_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_CLOSE_BRACE_CTRL_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_CLOSE_BRACE_ALT_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_CLOSE_BRACE_ALONE_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_CLOSE_BRACE_SHIFT_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_CLOSE_BRACE_CTRL_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_CLOSE_BRACE_ALT_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_BACK_SLASH_OR_PIPELINE_ALONE_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_BACK_SLASH_OR_PIPELINE_SHIFT_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_BACK_SLASH_OR_PIPELINE_CTRL_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_BACK_SLASH_OR_PIPELINE_ALT_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_SEMICOLON_OR_DOUBLE_POINT_ALONE_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_SEMICOLON_OR_DOUBLE_POINT_SHIFT_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_SEMICOLON_OR_DOUBLE_POINT_CTRL_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_SEMICOLON_OR_DOUBLE_POINT_ALT_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_COMMA_OR_SMALLER_THAN_ALONE_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_COMMA_OR_SMALLER_THAN_SHIFT_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_COMMA_OR_SMALLER_THAN_CTRL_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_COMMA_OR_SMALLER_THAN_ALT_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_SLASH_OR_QUESTION_MARK_ALONE_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_SLASH_OR_QUESTION_MARK_SHIFT_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_SLASH_OR_QUESTION_MARK_CTRL_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VK_SLASH_OR_QUESTION_MARK_ALT_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
ENDDEFINE
*------------------------------------------------------------------------------------------------------------------------*
*--@title:			LOGIC CLASS
*--@description:	Clase para las constantes logicas.
*--@autor:			Irwin R. <irwinrodriguez@adsecuador.com>
*--@version:		SNV: 1.2.0
*--@date:			2019-01-16
*------------------------------------------------------------------------------------------------------------------------*
DEFINE CLASS LOGIC AS CUSTOM
*-- Properties
	TRUE	= .T.
	FALSE	= .F.
	FUNCTION TRUE_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION FALSE_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
ENDDEFINE

*------------------------------------------------------------------------------------------------------------------------*
*--@title:			MSG CLASS
*--@description:	Clase para las constantes relacionadas la función MESSAGEBOX().
*--@autor:			Irwin R. <irwinrodriguez@adsecuador.com>
*--@version:		SNV: 1.2.0
*--@date:			2019-01-16
*------------------------------------------------------------------------------------------------------------------------*
DEFINE CLASS MSG AS CUSTOM

*-- Buttons
	OK_BUTTON					= 0
	OK_CANCEL_BUTTONS			= 1
	ABORT_RETRY_IGNORE_BUTTONS	= 2
	YES_NO_CANCEL_BUTTONS		= 3
	YES_NO_BUTTONS				= 4
	RETRY_CANCEL_BUTTONS		= 5

*-- Icons
	INFORMATION_ICON			= 64
	WARNING_ICON				= 48
	ERROR_ICON					= 16
	QUESTION_MARK				= 32

*-- Response
	Result						= 0
	OK							= 1
	CANCEL						= 2
	ABORT						= 3
	RETRY						= 4
	IGNORE						= 5
	YES							= 6
	NO							= 7

*-- Protección de las constantes.
	FUNCTION OK_BUTTON_ASSIGN
		PARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION OK_CANCEL_BUTTONS_ASSIGN
		PARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION ABORT_RETRY_IGNORE_BUTTONS_ASSIGN
		PARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION YES_NO_CANCEL_BUTTONS_ASSIGN
		PARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION YES_NO_BUTTONS_ASSIGN
		PARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION RETRY_CANCEL_BUTTONS_ASSIGN
		PARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION INFORMATION_ICON_ASSIGN
		PARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION WARNING_ICON_ASSIGN
		PARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION ERROR_ICON_ASSIGN
		PARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION QUESTION_MARK_ASSIGN
		PARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION OK_ASSIGN
		PARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION CANCEL_ASSIGN
		PARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION ABORT_ASSIGN
		PARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION RETRY_ASSIGN
		PARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION IGNORE_ASSIGN
		PARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION YES_ASSIGN
		PARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION NO_ASSIGN
		PARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
ENDDEFINE

*------------------------------------------------------------------------------------------------------------------------*
*--@title:			HTTP CLASS
*--@description:	Clase para las constantes releacionadas con las peticiones Http.
*--@autor:			Irwin R. <irwinrodriguez@adsecuador.com>
*--@version:		SNV: 1.2.0
*--@date:			2019-01-16
*------------------------------------------------------------------------------------------------------------------------*
DEFINE CLASS HTTP AS CUSTOM
*-- Respuestas Afirmativas 	1xx
	CONTINUE						= 100
	SWITCHING_PROTOCOLS				= 101
	PROCESSING						= 102
	CHECKPOINT						= 103

*-- Peticiones Correctas	2xx
	OK								= 200
	CREATED							= 201
	ACCEPTED						= 202
	NON_AUTHORITATIVE_INFORMATION	= 203
	NO_CONTENT						= 204
	RESET_CONTENT					= 205
	PARTIAL_CONTENT					= 206
	MULTI_STATUS					= 207
	ALREADY_REPORTED				= 208

*-- Redirecciones 3xx
	MULTIPLE_CHOICE					= 300
	MOVED_PERMANENTLY				= 301
	FOUND							= 302
	SEE_OTHER						= 303
	NOT_MODIFIED					= 304
	USE_PROXY						= 305
	SWITCH_PROXY					= 306
	TEMPORARY_REDIRECT				= 307
	PERMANENT_REDIRECT				= 308

*-- Errores del Cliente 4xx
	BAD_REQUEST						= 400
	UNAUTHORIZED					= 401
	PAYMENT_REQUIRED				= 402
	FORBIDDEN						= 403
	NOT_FOUND						= 404
	METHOD_NOT_ALLOWED				= 405
	NOT_ACCEPTABLE					= 406
	PROXY_AUTHENTICATION_REQUIRED	= 407
	REQUEST_TIMEOUT					= 408
	CONFLICT						= 409
	GONE							= 410
	LENGTH_REQUIRED					= 411
	PRECONDITION_FAILED				= 412
	REQUEST_ENTITY_TOO_LARGE		= 413
	REQUEST_URI_TOO_LONG			= 414
	UNSUPPORTED_MEDIA_TYPE			= 415
	REQUESTED_RANGE_NOT_ATISFIABLE	= 416
	EXPECTATION_FAILED				= 417
	IM_A_TEAPOT						= 418
	UNPROCESSABLE_ENTITY			= 422
	LOCKED							= 423
	FAILED_DEPENDENCY				= 424
	UNASSIGNED						= 425
	UPGRADE_REQUIRED				= 426
	PRECONDITION_REQUIRED			= 428
	TOO_MANY_REQUESTS				= 429
	REQUEST_HEADER_FIELDS_TOO_LARGE	= 431
	MICROSOFT_EXTENTION				= 449
	UNAVAILABLE_FOR_LEGAL_REASONS	= 451

*-- Errores del servidor 5xx
	INTERNAL_SERVER_ERROR			= 500
	NOT_IMPLEMENTED					= 501
	BAD_GATEWAY						= 502
	SERVICE_UNAVAILABLE				= 503
	GATEWAY_TIMEOUT					= 504
	HTTP_VERSION_NOT_SUPPORTED		= 505
	VARIANT_ALSO_NEGOTIATES			= 506
	INSUFFICIENT_STORAGE			= 507
	LOOP_DETECTED					= 508
	BANDWIDTH_LIMIT_EXCEEDED		= 509
	NOT_EXTENDED					= 510
	NETWORK_AUTHENTICATION_REQUIRED	= 511
	NOT_UPDATED						= 512
	VERSION_MISMATCH				= 521

*-- Respuestas Afirmativas 	1xx
	FUNCTION CONTINUE_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION SWITCHING_PROTOCOLS_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION PROCESSING_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION CHECKPOINT_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
*-- Peticiones Correctas	2xx
	FUNCTION OK_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION CREATED_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION ACCEPTED_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION NON_AUTHORITATIVE_INFORMATION_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION NO_CONTENT_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION RESET_CONTENT_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION PARTIAL_CONTENT_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION MULTI_STATUS_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION ALREADY_REPORTED_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
*-- Redirecciones 3xx
	FUNCTION MULTIPLE_CHOICE_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION MOVED_PERMANENTLY_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION FOUND_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION SEE_OTHER_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION NOT_MODIFIED_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION USE_PROXY_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION SWITCH_PROXY_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION TEMPORARY_REDIRECT_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION PERMANENT_REDIRECT_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
*-- Errores del Cliente 4xx
	FUNCTION BAD_REQUEST_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION UNAUTHORIZED_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION PAYMENT_REQUIRED_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION FORBIDDEN_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION NOT_FOUND_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION METHOD_NOT_ALLOWED_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION NOT_ACCEPTABLE_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION PROXY_AUTHENTICATION_REQUIRED_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION REQUEST_TIMEOUT_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION CONFLICT_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION GONE_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION LENGTH_REQUIRED_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION PRECONDITION_FAILED_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION REQUEST_ENTITY_TOO_LARGE_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION REQUEST_URI_TOO_LONG_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION UNSUPPORTED_MEDIA_TYPE_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION REQUESTED_RANGE_NOT_ATISFIABLE_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION EXPECTATION_FAILED_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION IM_A_TEAPOT_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION UNPROCESSABLE_ENTITY_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION LOCKED_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION FAILED_DEPENDENCY_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION UNASSIGNED_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION UPGRADE_REQUIRED_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION PRECONDITION_REQUIRED_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION TOO_MANY_REQUESTS_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION REQUEST_HEADER_FIELDS_TOO_LARGE_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION MICROSOFT_EXTENTION_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION UNAVAILABLE_FOR_LEGAL_REASONS_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
*-- Errores del servidor 5xx
	FUNCTION INTERNAL_SERVER_ERROR_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION NOT_IMPLEMENTED_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION BAD_GATEWAY_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION SERVICE_UNAVAILABLE_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION GATEWAY_TIMEOUT_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION HTTP_VERSION_NOT_SUPPORTED_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VARIANT_ALSO_NEGOTIATES_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION INSUFFICIENT_STORAGE_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION LOOP_DETECTED_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION BANDWIDTH_LIMIT_EXCEEDED_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION NOT_EXTENDED_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION NETWORK_AUTHENTICATION_REQUIRED_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION NOT_UPDATED_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
	FUNCTION VERSION_MISMATCH_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
ENDDEFINE
*------------------------------------------------------------------------------------------------------------------------*
*--@title:			UTILS CLASS
*--@description:	Carga todas las constantes miscelaneas.
*--@autor:			Irwin R. <irwinrodriguez@adsecuador.com>
*--@version:		SNV: 1.2.0
*--@date:			2019-01-17
*------------------------------------------------------------------------------------------------------------------------*
DEFINE CLASS UTILS AS CUSTOM
	CRLF 					= CHR(13)+CHR(10)
	CR 						= CHR(13)
	AMPERSAND				= CHR(38)
	
	*-- Properties Protection
	FUNCTION CRLF_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC	
	FUNCTION CR_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC	
	FUNCTION AMPERSAND_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC
ENDDEFINE
*------------------------------------------------------------------------------------------------------------------------*
*--@title:			CONST CLASS
*--@description:	Carga las constantes del sistema.
*--@autor:			Irwin R. <irwinrodriguez@adsecuador.com>
*--@version:		SNV: 1.2.0
*--@date:			2019-01-16
*------------------------------------------------------------------------------------------------------------------------*
DEFINE CLASS CONST AS CUSTOM

*-- Properties as Object
	KEYS		= .NULL.
	LOGIC		= .NULL.
	HTTP		= .NULL.
	MSG			= .NULL.
	UTILS		= .NULL.
	
*-- Load the keyboard constants
	FUNCTION INIT
		THIS.KEYS 	= CREATEOBJECT("KEYBOARD")
		THIS.LOGIC	= CREATEOBJECT("LOGIC")
		THIS.HTTP	= CREATEOBJECT("HTTP")
		THIS.MSG	= CREATEOBJECT("MSG")
		THIS.UTILS	= CREATEOBJECT("UTILS")
	ENDFUNC
ENDDEFINE
*------------------------------------------------------------------------------------------------------------------------*
*--@title:			CONST CLASS
*--@description:	Carga las constantes del sistema.
*--@autor:			Irwin R. <irwinrodriguez@adsecuador.com>
*--@version:		SNV: 1.2.0
*--@date:			2019-01-18
*------------------------------------------------------------------------------------------------------------------------*
DEFINE CLASS TYPES AS CUSTOM
	BLOB		= "W"
	CHAR 		= "C"
	CHARACTER	= "C"
	CURRENCY	= "Y"
	DATE 		= "D"
	DATETIME 	= "T"
	DOUBLE 		= "B"
	GENERAL 	= "G"
	INT 		= "I"
	INTEGER 	= "I"
	INT16 		= "I"
	INT32		= "I"
	LOGICAL		= "L"
	BOOL 		= "L"
	BOOLEAN		= "L"
	MEMO		= "M"
	TEXT		= "M"
	LONGTEXT	= "M"
	NUM 		= "N"
	NUMERIC		= "N"
	NUMBER		= "N"
	DECIMAL		= "N"
	DOUBLE 		= "N"
	FLOAT		= "F"
	VARBINARY	= "Q"
	VARCHAR		= "V"
	UNKNOW		= "U"
	NULL		= "X"
	OBJECT 		= "O"

	FUNCTION BLOB_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC			
	FUNCTION CHAR_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC	 		
	FUNCTION CHARACTER_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC		
	FUNCTION CURRENCY_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC		
	FUNCTION DATE_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC	 		
	FUNCTION DATETIME_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC	 	
	FUNCTION DOUBLE_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC	 		
	FUNCTION GENERAL_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC	 	
	FUNCTION INT_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC	 		
	FUNCTION INTEGER_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC	 	
	FUNCTION INT16_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC	 		
	FUNCTION INT32_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC			
	FUNCTION LOGICAL_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC			
	FUNCTION BOOL_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC	 		
	FUNCTION BOOLEAN_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC			
	FUNCTION MEMO_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC			
	FUNCTION TEXT_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC			
	FUNCTION LONGTEXT_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC		
	FUNCTION NUM_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC	 		
	FUNCTION NUMERIC_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC			
	FUNCTION NUMBER_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC			
	FUNCTION DECIMAL_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC			
	FUNCTION DOUBLE_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC	 		
	FUNCTION FLOAT_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC			
	FUNCTION VARBINARY_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC		
	FUNCTION VARCHAR_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC			
	FUNCTION UNKNOW_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC			
	FUNCTION NULL_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC			
	FUNCTION OBJECT_ASSIGN
		LPARAMETERS vNewVal
		RETURN .NULL.
	ENDFUNC	 			
ENDDEFINE
*------------------------------------------------------------------------------------------------------------------------*
*--@title:			LOAD_CONSTANTS
*--@description:	Carga todas las constantes del sistema en variables publicas.
*--@autor:			Irwin R. <irwinrodriguez@adsecuador.com>
*--@version:		SNV: 1.2.0
*--@date:			2019-01-16
*------------------------------------------------------------------------------------------------------------------------*
PROCEDURE LOAD_CONSTANTS

*-- Public CONST variable
	IF TYPE("CONST") = "U"
		PUBLIC CONST AS OBJECT
	ELSE &&TYPE("CONST") = "U"
	ENDIF &&TYPE("CONST") = "U"

*-- Public KEYS variable
	IF TYPE("KEYS") = "U"
		PUBLIC KEYS AS OBJECT
	ELSE &&TYPE("KEYS") = "U"
	ENDIF &&TYPE("KEYS") = "U"

*-- Public LOGIC variable
	IF TYPE("LOGIC") = "U"
		PUBLIC LOGIC AS OBJECT
	ELSE &&TYPE("LOGIC") = "U"
	ENDIF &&TYPE("LOGIC") = "U"

*-- Public HTTP variable
	IF TYPE("HTTP") = "U"
		PUBLIC HTTP AS OBJECT
	ELSE &&TYPE("HTTP") = "U"
	ENDIF &&TYPE("HTTP") = "U"

*-- Public MSG variable
	IF TYPE("MSG") = "U"
		PUBLIC MSG AS OBJECT
	ELSE &&TYPE("MSG") = "U"
	ENDIF &&TYPE("MSG") = "U"

*-- Public UTILS variable
	IF TYPE("UTILS") = "U"
		PUBLIC UTILS AS OBJECT
	ELSE &&TYPE("UTILS") = "U"
	ENDIF &&TYPE("UTILS") = "U"

*-- Public TYPES variable
	IF TYPE("TYPES") = "U"
		PUBLIC TYPES AS OBJECT
	ELSE &&TYPE("TYPES") = "U"
	ENDIF &&TYPE("TYPES") = "U"

	CONST = CREATEOBJECT("CONST")
	*-- Alternative constant usage
	KEYS 	= CONST.KEYS
	LOGIC	= CONST.LOGIC
	HTTP	= CONST.HTTP
	MSG		= CONST.MSG
	UTILS	= CONST.UTILS
	TYPES	= CONST.TYPES
ENDPROC
